language: python
python:
  - "2.7"
  - "3.4"
install:
    - pip install -r requirements.txt
    - pip install coveralls
addons:
  postgresql: "9.4"
script:
  - coverage run --source=hc manage.py test
after_success: coveralls
