language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient reportlab
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
addons:
  postgresql: "9.6"
script:
  - coverage run --omit=*/tests/* --source=hc manage.py test
after_success: coveralls
cache: pip
